name: fruchtlabor teamspeak bot frontend deploy - stage
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - stage

env:
  NAME: fruchtlabor-ts-bot-frontend-stage

  EXPOSED_HOST: ${{ vars.STAGE_EXPOSED_HOST }}
  EXPOSED_PORT: ${{ vars.STAGE_EXPOSED_PORT }}
  INTERNAL_PORT: ${{ vars.STAGE_INTERNAL_PORT }}

  MONGODB_CONNECT: ${{ secrets.STAGE_MONGODB_CONNECT }}
  MONGODB_DBNAME: ${{ vars.STAGE_MONGODB_DBNAME }}
  TEAMSPEAK_API_URL: ${{ vars.STAGE_TEAMSPEAK_API_URL }}
  TEAMSPEAK_SERVER_API_TOKEN: ${{ secrets.STAGE_TEAMSPEAK_SERVER_API_TOKEN }}
  JWT_SECRET: ${{ secrets.STAGE_JWT_SECRET }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Run docker container
        run: docker compose -f .gitea/docker-compose.yml -p ${NAME} up --build -d
      - name: Ping
        run: |
          echo "Ping service on ${EXPOSED_HOST}:${EXPOSED_PORT} in 10 seconds..."
          sleep 10

          HTTP_RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null "${EXPOSED_HOST}:${EXPOSED_PORT}")
          if [ "$HTTP_RESPONSE" -lt 500 ]; then
            echo "Address is available."
          else
            echo "Address is not available."
            exit 1
          fi
