services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - INTERNAL_PORT=${INTERNAL_PORT}
        - MONGODB_CONNECT=${MONGODB_CONNECT}
        - MONGODB_DBNAME=${MONGODB_DBNAME}
        - TEAMSPEAK_API_URL=${TEAMSPEAK_API_URL}
        - JWT_SECRET=${JWT_SECRET}
    image: ${NAME}:latest
    container_name: ${NAME}
    restart: unless-stopped
    environment:
      - MONGODB_CONNECT=${MONGODB_CONNECT}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - TEAMSPEAK_API_URL=${TEAMSPEAK_API_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${EXPOSED_HOST}:${EXPOSED_PORT}:${INTERNAL_PORT}"
