services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        - INTERNAL_PORT=80
    image: fruchtlabor-ts-bot-frontend-local-dev:latest
    container_name: fruchtlabor-ts-bot-frontend-local-dev
    restart: unless-stopped
    # environment:
    ports:
      - "0.0.0.0:3000:80"
    volumes:
      - ../public:/app/public
      - ../src:/app/src
