services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - INTERNAL_PORT=${INTERNAL_PORT}
        - MONGODB_CONNECT=${MONGODB_CONNECT}
        - MONGODB_DBNAME=${MONGODB_DBNAME}
        - NEXT_PUBLIC_TEAMSPEAK_API_URL=${NEXT_PUBLIC_TEAMSPEAK_API_URL}
    image: ${NAME}-${ENVIRONMENT}:latest
    container_name: ${NAME}-${ENVIRONMENT}
    restart: unless-stopped
    environment:
      - MONGODB_CONNECT=${MONGODB_CONNECT}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - NEXT_PUBLIC_TEAMSPEAK_API_URL=${NEXT_PUBLIC_TEAMSPEAK_API_URL}
    ports:
      - "${EXPOSED_HOST}:${EXPOSED_PORT}:${INTERNAL_PORT}"
    networks:
      - ${NAME}-${ENVIRONMENT}

networks:
  ${NAME}-${ENVIRONMENT}:
    driver: bridge
