services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${NAME}:latest
    container_name: ${NAME}
    restart: unless-stopped
    environment:
      - MONGODB_CONNECT=${MONGODB_CONNECT}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
    ports:
      - "${EXPOSED_HOST}:${EXPOSED_PORT}:${INTERNAL_PORT}"
