services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${NAME}:latest
    container_name: ${NAME}
    restart: unless-stopped
    environment:
    ports:
      - "${EXPOSED_HOST}:${EXPOSED_PORT}:${INTERNAL_PORT}"
